# Generated by Django 4.2.6 on 2023-11-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(unique=True, verbose_name='Email')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('segundo_nome', models.CharField(max_length=30, verbose_name='Segundo Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('e_admin', models.BooleanField(default=False, verbose_name='E Administrador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
