# Generated by Django 4.2.6 on 2023-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(unique=True, verbose_name='Username'),
        ),
    ]
