version: "3.9"

services:

  pg:
    build: 
      dockerfile: ./docker/pg.Dockerfile
      context: .
    image: webmobile/pg
    container_name: pg
    ports: 
      - "5432:5432"
    env_file:
      - ./dotenv_files/.env
    networks: 
      - nw-webmobile
    volumes: 
      - pgdata:/var/lib/postgresql/data/

  api:
    build:
       dockerfile: ./docker/api.Dockerfile
       context: .
    image: webmobile/api
    container_name: api
    ports: 
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    networks: 
      - nw-webmobile
    depends_on:
      - "pg"



networks: 
  nw-webmobile:
    driver: bridge

volumes: 
  pgdata: